feat: update gh actions

diff --git a/.github/workflows/release-binaries.yaml b/.github/workflows/release-binaries.yaml
--- a/.github/workflows/release-binaries.yaml
+++ b/.github/workflows/release-binaries.yaml
@@ -1,4 +1,4 @@
-name: Compile into binaries
+name: binaries-release
 
 on:
   release:
@@ -16,9 +16,61 @@ permissions:
   packages: write
 
 jobs:
-  releases-matrix:
+  check-versions:
+    name: check repo versions
+    runs-on: ubuntu-latest
+    outputs:
+      version: ${{ steps.config.outputs.version }}
+      gover: ${{ steps.config.outputs.gover }}
+      commit: ${{ steps.config.outputs.commit }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Configure
+        id: config
+        run: |
+          if [ "${{ github.event_name }}" = "release" ]; then
+            export RELEASE_INPUT="${{ github.ref_name }}"
+          elif [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
+            export RELEASE_INPUT="${{ inputs.release }}"
+          fi
+          if [ -z ${RELEASE_INPUT} ]; then
+            echo "[ERROR] empty 'RELEASE_INPUT'."
+            exit 1
+          fi
+          version=${RELEASE_INPUT}
+          gover=$(grep '^go ' go.mod | awk '{print $2}')
+          commit=$(git rev-parse --short HEAD)
+          
+          if [ "${version}" = "$(cat version)" ]; then
+            echo "version=${version}" >> $GITHUB_OUTPUT
+            echo "gover=${gover}" >> $GITHUB_OUTPUT
+            echo "commit=${commit}" >> $GITHUB_OUTPUT
+            exit 0
+          else
+          echo -n "${version}" > version
+
+          author_name=$(git log -1 --pretty=format:'%an')
+          author_email=$(git log -1 --pretty=format:'%ae')
+          git config user.name "${author_name}"
+          git config user.email "${author_email}"
+          git add .
+          git commit -m "feat: [bot] set new '${{ inputs.release }}' version"
+          git push origin ${{ github.event.repository.default_branch }}
+          
+          new_commit=$(git rev-parse --short HEAD)
+
+          echo "version=${version}" >> $GITHUB_OUTPUT
+          echo "gover=${gover}" >> $GITHUB_OUTPUT
+          echo "commit=${new_commit}" >> $GITHUB_OUTPUT
+
+  binary-matrix:
     name: Release Go Binary
     runs-on: ubuntu-latest
+    needs: check-versions
     strategy:
       matrix:
         # build and publish in parallel:
@@ -31,15 +83,20 @@ jobs:
           - goarch: arm64
             goos: windows
     steps:
-      - uses: actions/checkout@v3
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
       - uses: wangyoucao577/go-release-action@v1.31
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           goos: ${{ matrix.goos }}
           goarch: ${{ matrix.goarch }}
-          goversion: "https://dl.google.com/go/go1.22.3.linux-amd64.tar.gz"
+          goversion: "https://dl.google.com/go/go${{ needs.check-versions.outputs.gover }}.linux-amd64.tar.gz"
+          ldflags: "-X osproxy/internal/cmd/version.version=${{ needs.check-versions.outputs.version }} -X osproxy/internal/cmd/version.golang=${{ needs.check-versions.outputs.gover }} -X osproxy/internal/cmd/version.commit=${{ needs.check-versions.outputs.commit }}"
           project_path: "./cmd/"
           binary_name: "osproxy"
-          release_tag: ${{ inputs.release }}
+          release_tag: ${{ needs.check-versions.outputs.version }}
           overwrite: true
           extra_files: LICENSE README.md
